### ISSUE TITLE
Recipe for Grower Standing Stone produces Accelerating Standing Stone instead

### ISSUE THREAD

**Issue by Febilian** [PrinceOfAmber/RootsClassic#6]
The difference in the recipes appears to be the kind of bark used. The tablet lists the jungle bark as the ingredient for the Accelerating Standing Stone, but I put birch bark in the incense burner for the Grower stone's recipe and got the Accelerating stone as an output. Either the tablet is not showing the recipes properly, or the recipe itself has a mistake.

**Comment by PrinceOfAmber** [comment]
Ive got a fix coming for this.  I think its because so many stones used identical top row of ingredients (altar items), i changes some of those.  Also added tooltips and other helpful things.


![2018-08-05_15 29 52](https://user-images.githubusercontent.com/621529/43690749-69dce1a4-98c4-11e8-8ead-1c6b3d36b6d7.png)

**Comment by PrinceOfAmber** [comment]
Fixed in latest release . Report anything else you find :) 
https://minecraft.curseforge.com/projects/roots-classic/files/2599066
